apiVersion: 1

datasources:
  - name: Influx-DB
    type: influxdb
    access: proxy
    database: locust
    user: $GRAFANA_AUTH_USERNAME
    password: $GRAFANA_AUTH_PASSWORD
    url: http://influxdb:8086
    jsonData:

      httpMode: GET